# application-eureka2.yml
# 激活当前profile: --spring.profiles.active=eureka2

eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:2001/eureka